---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-v2
  labels:
    app: details
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: v2
  template:
    metadata:
      labels:
        app: details
        version: v2
    spec:
      serviceAccountName: bookinfo-details
      containers:
      - name: details
        image: docker.io/anichikage/book-detail-v2:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        securityContext:
          runAsUser: 1000